# Generated by Django 3.1.5 on 2021-02-04 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_type', models.IntegerField(default=1, verbose_name='language_type')),
                ('checked_status', models.BooleanField(default=False, verbose_name='checked_status')),
                ('repo_url', models.CharField(default='None', max_length=255, verbose_name='repo_url')),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='questions_id')),
            ],
        ),
    ]
