# Generated by Django 3.1.5 on 2021-01-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='repo_url',
            field=models.CharField(default='None', max_length=255, verbose_name='repo_url'),
        ),
    ]
