# Generated by Django 3.1.6 on 2021-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255, verbose_name='repo_name')),
                ('repo_full_name', models.CharField(max_length=255, verbose_name='repo_full_name')),
                ('private', models.BooleanField(default=False, verbose_name='private')),
                ('owner_login', models.CharField(max_length=255, verbose_name='owner_login')),
                ('owner_avatar_url', models.CharField(max_length=255, verbose_name='owner_avatar_url')),
                ('html_url', models.CharField(max_length=255, verbose_name='html_url')),
                ('clone_url', models.CharField(max_length=255, verbose_name='clone_url')),
                ('size', models.CharField(max_length=255, verbose_name='repo_size')),
                ('language', models.CharField(max_length=255, verbose_name='language')),
            ],
        ),
    ]
