# Generated by Django 3.1.6 on 2021-02-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repodetails', '0002_repodetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repodetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user_id'),
        ),
    ]
