# Generated by Django 3.1.6 on 2021-02-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repodetails', '0004_auto_20210215_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repodetail',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='language'),
        ),
    ]
